# Generated by Django 4.2.18 on 2025-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
    ]
