# Generated by Django 4.2.18 on 2025-06-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='company',
            field=models.CharField(choices=[('Google', 'Google'), ('Meta', 'Meta'), ('Amazon', 'Amazon'), ('Microsoft', 'Microsoft'), ('Apple', 'Apple'), ('Netflix', 'Netflix'), ('Tesla', 'Tesla'), ('Uber', 'Uber'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Spotify', 'Spotify'), ('Airbnb', 'Airbnb'), ('ByteDance', 'ByteDance'), ('Goldman Sachs', 'Goldman Sachs'), ('JPMorgan', 'JPMorgan'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
