# Generated by Django 5.2.4 on 2025-07-17 03:03
from django.db import migrations

def populate_problems(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    Problem.objects.bulk_create([
        Problem(
            title='Two Sum',
            statement='Given an array of integers, return indices of two numbers that add up to a target.',
            input_format='First line: array size n, second line: n integers, third line: target',
            output_format='Two indices as a list',
            sample_input='4\n2 7 11 15\n9',
            sample_output='[0, 1]',
            difficulty='Easy',
            tags='array,two-pointers',
            company='Google',
            created_at='2025-07-17 08:00:00'
        ),
        Problem(
            title='Reverse String',
            statement='Write a function that reverses a string.',
            input_format='One line with the string',
            output_format='Reversed string',
            sample_input='hello',
            sample_output='olleh',
            difficulty='Easy',
            tags='string',
            company='Facebook',
            created_at='2025-07-17 08:00:00'
        ),
    ])

class Migration(migrations.Migration):
    dependencies = [('problems', '0005_problem_company')]
    operations = [migrations.RunPython(populate_problems)]